name: testing_env_cadet_rdm
channels:
  - conda-forge
dependencies:
  - python=3.11
  - libiconv=1.17
  - openssl
  - cadet
  - jupyterlab-myst
  - jupyterlab
prefix: C:\Users\h.lanzrath\AppData\Local\miniforge3\envs\testing_env_cadet_rdm
